### ISSUE TITLE
PR_END_OF_FILE_ERROR

### ISSUE THREAD

**Issue by zzmishgun** [cbeuw/Cloak#247]
Hi, i have a PR_END_OF_FILE_ERROR or 500 Internal Privoxy Error
but the thing is, it works fine on my phone
```
2024-02-09 03:34:49.8429|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for *my vpsip:443* on 127.0.0.1:56487 - PID: 16444
2024-02-09 03:34:51.8631|WARN|Shadowsocks.Controller.TCPHandler|System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
2024-02-09 03:34:51.8631|WARN|Shadowsocks.Controller.TCPHandler|System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
2024-02-09 03:34:51.8631|WARN|Shadowsocks.Controller.TCPHandler|System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
2024-02-09 03:34:52.6339|DEBUG|Shadowsocks.Controller.TCPHandler|connect to www.google.com:443
2024-02-09 03:34:52.6495|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for *my vpsip:443* on 127.0.0.1:56496 - PID: 10732
2024-02-09 03:34:54.6707|WARN|Shadowsocks.Controller.TCPHandler|System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
2024-02-09 03:34:58.4495|DEBUG|Shadowsocks.Controller.TCPHandler|connect to support.librewolf.net:443
2024-02-09 03:34:58.4495|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for *my vpsip:443* on 127.0.0.1:56501 - PID: 4964
2024-02-09 03:35:00.4700|WARN|Shadowsocks.Controller.TCPHandler|System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
2024-02-09 03:35:09.4556|DEBUG|Shadowsocks.Controller.TCPHandler|connect to yandex.ru:443
2024-02-09 03:35:09.4556|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for *my vpsip:443* on 127.0.0.1:56509 - PID: 9140
2024-02-09 03:35:11.4669|WARN|Shadowsocks.Controller.TCPHandler|System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
2024-02-09 03:35:14.1530|DEBUG|Shadowsocks.Controller.TCPHandler|connect to yandex.ru:80
2024-02-09 03:35:14.1530|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for *my vpsip:443* on 127.0.0.1:56514 - PID: 12896
2024-02-09 03:35:16.1630|WARN|Shadowsocks.Controller.TCPHandler|System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
2024-02-09 03:35:18.1365|DEBUG|Shadowsocks.Controller.TCPHandler|connect to bing.com:443
2024-02-09 03:35:18.1521|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for *my vpsip:443* on 127.0.0.1:56521 - PID: 15100
2024-02-09 03:35:20.1925|WARN|Shadowsocks.Controller.TCPHandler|System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
2024-02-09 03:35:31.0665|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: en-US
2024-02-09 03:35:31.0665|DEBUG|Shadowsocks.Controller.PACServer|Set PAC URL:http://127.0.0.1:1080/pac?hash=oSVkynAHCcedoIUMJRgi9w2
2024-02-09 03:35:31.2045|INFO|Shadowsocks.Controller.ShadowsocksController|Started SIP003 plugin for *my vpsip:443* on 127.0.0.1:56524 - PID: 11760
2024-02-09 03:35:31.2201|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.1.0)
2024-02-09 03:35:31.2201|DEBUG|Shadowsocks.Controller.Listener|
```
i get PR_END_OF_FILE_ERROR or 
```
500 Internal Privoxy Error

Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).
```
depends on a site i try to visit
```
Encryption:     chacha20-ietf-poly1305
Cloak Proxy Method:   shadowsocks
Cloak UID:            fhFzskKgwPGoFje4fhQEXA==
Cloak Public Key:     *my key*
Cloak Encryption:     plain
Cloak Server Name:    Domain or ip of RedirAddr (Default bing.com)
Cloak NumConn:        4 or more
Cloak MaskBrowser:    firefox or chrome
Cloak StreamTimeout:    300
```

**Comment by zzmishgun** [comment]
problem is solved by switching my dns to quad9, but i am still not sure why it didnt work on my windows machine with google dns, but worked on my phone, so i will leave this ticket open, hope some1 smarter than me will be able to explain.
